@php
    $initialCourses = $selectedCourses->map(fn ($course) => [
        'id' => (int) $course->id,
        'title' => $course->title,
        'priceLabel' => $course->price_label,
    ])->values();
@endphp
<div class="space-y-6">
    <div class="grid gap-5 sm:grid-cols-2">
        <div class="sm:col-span-2"><label class="block text-sm font-semibold text-gray-700">Judul</label><input name="title" value="{{ old('title', $learningPath->title) }}" required class="mt-1.5 w-full rounded-lg border-gray-300 focus:border-bass-red focus:ring-bass-red">@error('title')<p class="mt-1 text-sm text-error">{{ $message }}</p>@enderror</div>
        <div class="sm:col-span-2"><label class="block text-sm font-semibold text-gray-700">Slug</label><input name="slug" value="{{ old('slug', $learningPath->slug) }}" class="mt-1.5 w-full rounded-lg border-gray-300 focus:border-bass-red focus:ring-bass-red" placeholder="otomatis-dari-judul">@error('slug')<p class="mt-1 text-sm text-error">{{ $message }}</p>@enderror</div>
        <div class="sm:col-span-2"><label class="block text-sm font-semibold text-gray-700">Deskripsi Singkat</label><input name="short_description" value="{{ old('short_description', $learningPath->short_description) }}" maxlength="500" class="mt-1.5 w-full rounded-lg border-gray-300 focus:border-bass-red focus:ring-bass-red">@error('short_description')<p class="mt-1 text-sm text-error">{{ $message }}</p>@enderror</div>
        <div class="sm:col-span-2"><label class="block text-sm font-semibold text-gray-700">Deskripsi</label><textarea name="description" rows="5" class="mt-1.5 w-full rounded-lg border-gray-300 focus:border-bass-red focus:ring-bass-red">{{ old('description', $learningPath->description) }}</textarea>@error('description')<p class="mt-1 text-sm text-error">{{ $message }}</p>@enderror</div>
    </div>
    <fieldset x-data="learningPathCoursePicker()" x-init="loadCourses()" class="space-y-3">
        <div><legend class="text-sm font-semibold text-gray-700">Urutan Course</legend><p class="mt-1 text-xs text-gray-500">Pilih minimal dua course. Semua course tetap didaftarkan atau dibeli secara terpisah.</p>@error('course_ids')<p class="mt-2 text-sm text-error">{{ $message }}</p>@enderror @error('course_ids.*')<p class="mt-2 text-sm text-error">{{ $message }}</p>@enderror</div>
        <div class="grid gap-4 lg:grid-cols-2">
            <section class="overflow-hidden rounded-xl border border-gray-200 bg-white"><div class="border-b border-gray-200 bg-gray-50 p-4"><div class="flex items-center justify-between gap-3"><h3 class="text-sm font-semibold text-gray-900">Cari Course</h3><span class="text-xs text-gray-500" x-text="meta.total + ' ditemukan'"></span></div><input type="search" x-model="query" @input.debounce.350ms="loadCourses(1)" class="mt-3 w-full rounded-lg border-gray-300 text-sm focus:border-bass-red focus:ring-bass-red" placeholder="Ketik judul course..."></div>
                <div class="relative min-h-72"><div x-show="loading" class="absolute inset-0 z-10 flex items-center justify-center bg-white/80"><span class="text-sm font-medium text-gray-500">Memuat course...</span></div><div x-show="errorMessage" x-cloak class="m-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700" x-text="errorMessage"></div><div x-show="!loading && courses.length === 0 && !errorMessage" x-cloak class="flex min-h-72 items-center justify-center p-6 text-center text-sm text-gray-500">Tidak ada course yang cocok.</div><ul x-show="courses.length > 0" class="divide-y divide-gray-100"><template x-for="course in courses" :key="course.id"><li class="flex items-center justify-between gap-3 p-4"><div class="min-w-0"><p class="truncate text-sm font-semibold text-gray-900" x-text="course.title"></p><p class="mt-0.5 text-xs text-gray-500" x-text="course.priceLabel"></p></div><button type="button" @click="addCourse(course)" :disabled="isSelected(course.id)" class="shrink-0 rounded-lg border px-3 py-1.5 text-xs font-semibold disabled:cursor-not-allowed disabled:border-gray-200 disabled:bg-gray-100 disabled:text-gray-400" :class="isSelected(course.id) ? '' : 'border-bass-red text-bass-red hover:bg-red-50'" x-text="isSelected(course.id) ? 'Terpilih' : 'Tambah'"></button></li></template></ul></div>
                <div x-show="meta.lastPage > 1" x-cloak class="flex items-center justify-between border-t border-gray-200 bg-gray-50 px-4 py-3"><button type="button" @click="loadCourses(meta.currentPage - 1)" :disabled="loading || meta.currentPage === 1" class="rounded-md border border-gray-300 px-3 py-1.5 text-xs font-semibold disabled:opacity-40">Sebelumnya</button><span class="text-xs text-gray-500" x-text="'Halaman ' + meta.currentPage + ' dari ' + meta.lastPage"></span><button type="button" @click="loadCourses(meta.currentPage + 1)" :disabled="loading || meta.currentPage === meta.lastPage" class="rounded-md border border-gray-300 px-3 py-1.5 text-xs font-semibold disabled:opacity-40">Berikutnya</button></div>
            </section>
            <section class="overflow-hidden rounded-xl border border-gray-200 bg-white"><div class="flex items-center justify-between border-b border-gray-200 bg-gray-50 p-4"><div><h3 class="text-sm font-semibold text-gray-900">Course Terpilih</h3><p class="mt-0.5 text-xs text-gray-500" x-text="selected.length + ' course'"></p></div><span class="rounded-full px-2.5 py-1 text-xs font-semibold" :class="selected.length >= 2 ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'" x-text="selected.length >= 2 ? 'Siap' : 'Minimal 2'"></span></div><div x-show="selected.length === 0" x-cloak class="flex min-h-72 items-center justify-center p-6 text-center text-sm text-gray-500">Belum ada course dipilih.</div><ol x-show="selected.length > 0" x-cloak class="max-h-[32rem] divide-y divide-gray-100 overflow-y-auto"><template x-for="(course, index) in selected" :key="course.id"><li class="flex items-center gap-3 p-4"><input type="hidden" name="course_ids[]" :value="course.id"><span class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-gray-100 text-xs font-bold text-gray-600" x-text="index + 1"></span><div class="min-w-0 flex-1"><p class="truncate text-sm font-semibold text-gray-900" x-text="course.title"></p><p class="mt-0.5 text-xs text-gray-500" x-text="course.priceLabel"></p></div><div class="flex shrink-0 items-center gap-1"><button type="button" @click="moveCourse(index, -1)" :disabled="index === 0" class="rounded-md p-1.5 text-gray-500 disabled:opacity-30" aria-label="Naikkan urutan course">↑</button><button type="button" @click="moveCourse(index, 1)" :disabled="index === selected.length - 1" class="rounded-md p-1.5 text-gray-500 disabled:opacity-30" aria-label="Turunkan urutan course">↓</button><button type="button" @click="removeCourse(index)" class="rounded-md p-1.5 text-gray-400 hover:text-red-600" aria-label="Hapus course">✕</button></div></li></template></ol></section>
        </div>
    </fieldset>
    <input type="hidden" name="is_active" value="0"><label class="flex items-center gap-3 rounded-xl border border-gray-200 p-4"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $learningPath->is_active)) class="rounded border-gray-300 text-bass-red focus:ring-bass-red"><span><strong class="block text-sm text-gray-900">Aktif di katalog</strong><span class="text-xs text-gray-500">Learning path tampil jika memiliki minimal dua course yang eligible.</span></span></label>
    <div class="flex justify-end gap-3"><a href="{{ route('admin.learning-paths.index') }}" class="rounded-lg border border-gray-300 px-5 py-2.5 font-semibold text-gray-700 hover:bg-gray-50">Batal</a><button class="rounded-lg bg-bass-red px-5 py-2.5 font-semibold text-white hover:bg-bass-red-hover">Simpan Learning Path</button></div>
</div>
@push('scripts')<script>
function learningPathCoursePicker() { return {
    endpoint: @js(route('admin.learning-paths.course-options')), selected: @js($initialCourses), courses: [], query: '', loading: false, errorMessage: '', requestNumber: 0, meta: { currentPage: 1, lastPage: 1, total: 0 },
    async loadCourses(page = 1) { const requestNumber = ++this.requestNumber; this.loading = true; this.errorMessage = ''; try { const url = new URL(this.endpoint, window.location.origin); url.searchParams.set('page', page); if (this.query.trim()) url.searchParams.set('q', this.query.trim()); const response = await fetch(url, { headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error(); const result = await response.json(); if (requestNumber !== this.requestNumber) return; this.courses = result.data; this.meta = result.meta; } catch (error) { if (requestNumber !== this.requestNumber) return; this.courses = []; this.meta = { currentPage: 1, lastPage: 1, total: 0 }; this.errorMessage = 'Course gagal dimuat. Silakan coba lagi.'; } finally { if (requestNumber === this.requestNumber) this.loading = false; } },
    isSelected(id) { return this.selected.some(course => Number(course.id) === Number(id)); }, addCourse(course) { if (!this.isSelected(course.id)) this.selected.push({ ...course }); }, removeCourse(index) { this.selected.splice(index, 1); }, moveCourse(index, direction) { const target = index + direction; if (target < 0 || target >= this.selected.length) return; const [course] = this.selected.splice(index, 1); this.selected.splice(target, 0, course); }
}; }
</script>@endpush
